name: 'Terraform Install'
description: 'Terraform install and version Setup by TFEnv.'
inputs:
  terraformVersion:
    description: 'Terraform Version.'
    default: '1.3.6'
    required: true

runs:
  using: "composite"
  steps:
  - name: TFEnv Install
    run: |
      git \
      clone \
      --depth=1 \
      https://github.com/tfutils/tfenv.git \
      ~/.tfenv && \
      echo  "$HOME/.tfenv/bin" >> $GITHUB_PATH
    shell: bash

  - name: Terraform Setup Version
    run: |
      tfenv install $terraformVersion && \
      tfenv use $terraformVersion
    shell: bash