name: 'Terragrunt Destroy'
description: 'Terragrunt Apply environment folders based and only branch.'
inputs:
  AWS_REGION:
    description: 'Terragrunt path region.'
    default: ''
    required: true
  TERRAFORM_VERSION:
    description: 'Terragrunt Version.'
    default: '1.3.8'
    required: true
  TERRAGRUNT_VERSION:
    description: 'Terragrunt Version.'
    default: '0.58.2'
    required: true

runs:
  using: "composite"
  steps:
    - name: AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ steps.paths_filter.outputs.AWS_ACCOUNT }}:role/GitHubActions
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Install
      uses: marquesmateus93/piperoad/templates/terraform@master
      env:
        TERRAFORM_VERSION: ${{ env.TERRAFORM_VERSION }}

    - name: Terragrunt Destroy
      uses: marquesmateus93/piperoad/templates/terragrunt/destroy@master
      env:
        TERRAGRUNT_VERSION: ${{ env.TERRAGRUNT_VERSION }}
        TERRAGRUNT_PATH:    ${{ steps.paths_filter.outputs.ENV_FOLDER }}/${{ env.AWS_REGION }}