name: 'Paths Filter'
description: ''

inputs:
  AWS_DEV_ACCOUNT:
    description: ''
    required: true
  AWS_STA_ACCOUNT:
    description: ''
    required: true
  AWS_PRO_ACCOUNT:
    description: ''
    required: true

runs:
  using: "composite"
  steps:
  - uses: dorny/paths-filter@v3
    id: filter
    with:
      filters: |
        dev:
          - 'dev/**'
        sta:
          - 'sta/**'
        pro:
          - 'pro/**'
    
  - name: Filter Output 
    run: |
      echo "AWS_ACCOUNT=$(${{ steps.filter.outputs.dev == 'true' && inputs.AWS_DEV_ACCOUNT || steps.filter.outputs.sta == 'true' && inputs.AWS_STA_ACCOUNT || github.ref == 'refs/heads/pro' && inputs.AWS_PRO_ACCOUNT}})"
      AWS_ACCOUNT >> $GITHUB_ENV
    shell: bash