name: 'Paths Filter'
description: 'AWS Account and Terragrunt folder environment setup based on project folder changes.'

inputs:
  AWS_DEV_ACCOUNT:
    description: 'Development account number.'
    required: true
  AWS_STA_ACCOUNT:
    description: 'Staging account number.'
    required: true
  AWS_PRO_ACCOUNT:
    description: 'Production account number.'
    required: true

outputs:
  AWS_ACCOUNT: 
    value: ${{ steps.filter_output.outputs.AWS_ACCOUNT }}
    description: 'Account number output.'
  ENV_FOLDER: 
    value: ${{ steps.filter_output.outputs.ENV_FOLDER }}
    description: 'Changed folder updated output.'

runs:
  using: "composite"

  steps:
  - uses: dorny/paths-filter@v3
    id: paths_filter
    with:
      filters: |
        dev:
          - 'dev/**'
        sta:
          - 'sta/**'
        pro:
          - 'pro/**'

  - name: Filter Output
    id: filter_output
    run: |
      if [ ${{ steps.paths_filter.outputs.dev }} == 'true' ]; then
        echo "AWS_ACCOUNT=$AWS_DEV_ACCOUNT" >> $GITHUB_OUTPUT
        echo "ENV_FOLDER=dev" >> $GITHUB_OUTPUT
      elif [ ${{ steps.paths_filter.outputs.dev }} == 'true' ]; then
        echo "AWS_ACCOUNT=$AWS_STA_ACCOUNT" >> $GITHUB_OUTPUT
        echo "ENV_FOLDER=sta" >> $GITHUB_OUTPUT
      elif [ ${{ steps.paths_filter.outputs.dev }} == 'true' ]; then
        echo "AWS_ACCOUNT=$AWS_PRO_ACCOUNT" >> $GITHUB_OUTPUT
        echo "ENV_FOLDER=pro" >> $GITHUB_OUTPUT
      else
        echo "Invalid 'AWS_ACCOUNT' and 'ENV_FOLDER' opntions!"
      fi
    shell: bash