name: 'Paths Filter'
description: ''

inputs:
  AWS_DEV_ACCOUNT:
    description: ''
    required: true
  AWS_STA_ACCOUNT:
    description: ''
    required: true
  AWS_PRO_ACCOUNT:
    description: ''
    required: true

outputs:
  AWS_ACCOUNT: 
    value: ${{ steps.filter_output.outputs.AWS_ACCOUNT }}
    description: ""

runs:
  using: "composite"

  steps:
  - uses: dorny/paths-filter@v3
    id: filter
    with:
      filters: |
        dev:
          - 'dev/**'
        sta:
          - 'sta/**'
        pro:
          - 'pro/**'

  - name: Filter Output
    id: filter_output
    run: |
      if [ ${{ steps.filter.outputs.dev }} == 'true' ]; then
        echo "AWS_ACCOUNT=$AWS_DEV_ACCOUNT" >> $GITHUB_ENV
        echo "AWS_ACCOUNT=$AWS_DEV_ACCOUNT"" >> $GITHUB_OUTPUT
      else
        echo "Else here!"
      fi

      echo "Valor: ${{ env.AWS_ACCOUNT }}"
    shell: bash

  - name: Simple Echo
    run: |
      echo "Output: ${{ steps.filter_output.outputs.AWS_ACCOUNT }}"
    shell: bash