name: 'Paths Filter'
description: ''

inputs:
  AWS_DEV_ACCOUNT:
    description: ''
    required: true
  AWS_STA_ACCOUNT:
    description: ''
    required: true
  AWS_PRO_ACCOUNT:
    description: ''
    required: true

runs:
  using: "composite"
  steps:
  - uses: dorny/paths-filter@v3
    id: filter
    with:
      filters: |
        dev:
          - 'dev/**'
        sta:
          - 'sta/**'
        pro:
          - 'pro/**'

  - name: Filter Output 
    run: |
      if [ ${{ steps.filter.outputs.dev == 'true' ]; then
        echo "AWS_ACCOUNT=${{ inputs.AWS_DEV_ACCOUNT }}" >> $GITHUB_ENV
      else
        echo "Else here!"
      fi
    shell: bash