name: 'Apply Path Based'
description: 'Terragrunt Apply environment folders based and only branch.'
inputs:
  AWS_REGION:
    description: 'AWS Terragrunt path region.'
    default: ''
    required: true
  AWS_DEV_ACCOUNT:
    description: 'Development account number.'
    required: true
  AWS_STA_ACCOUNT:
    description: 'Staging account number.'
    required: true
  AWS_PRO_ACCOUNT:
    description: 'Production account number.'
    required: true
  TERRAGRUNT_VERSION:
    description: 'Terragrunt Version.'
    default: '0.58.2'
    required: true
  TERRAGRUNT_PATH:
    description: 'Terragrunt path to the manifests tree.'
    default: ''
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Paths Filter
      id: paths_filter
      uses: marquesmateus93/piperoad/templates/paths-filter@master
      env:
        AWS_DEV_ACCOUNT:  ${{ env.AWS_DEV_ACCOUNT }}
        AWS_STA_ACCOUNT:  ${{ env.AWS_STA_ACCOUNT }}
        AWS_PRO_ACCOUNT:  ${{ env.AWS_PRO_ACCOUNT }}

    - name: AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ steps.paths_filter.outputs.AWS_ACCOUNT }}:role/GitHubActions
        aws-region: ${{ AWS_REGION }}

    - name: Terraform Install
      uses: marquesmateus93/piperoad/templates/terraform@master
      env:
        TERRAFORM_VERSION: ${{ env.TERRAFORM_VERSION }}

    - name: Terragrunt Apply
      uses: marquesmateus93/piperoad/templates/terragrunt@master
      env:
        TERRAGRUNT_VERSION: ${{ env.TERRAGRUNT_VERSION }}
        TERRAGRUNT_PATH:    ${{ steps.paths_filter.outputs.ENV_FOLDER }}/${{ env.AWS_REGION }}